### ISSUE TITLE
Not showing any of the installed ROMs

### ISSUE THREAD

**Issue by fmkguy** [spiritualized1997/openFPGA-GG#3]
After following the installation instructions and booting up the Pocket, none of my Game Gear ROMs are displaying. I've already gone through the core processes for GB/C and GBA without issue.

For clarity, all of the ROMs were placed in `Assets/gg/common`.

**Comment by Guspaz** [comment]
Make sure your roms are uncompressed and have the .gg extension.

**Comment by Guspaz** [comment]
Note that it's case sensitive, so "foo.GG" won't work.

**Comment by fmkguy** [comment]
AH! That has to be it. All of mine end in caps `.GG`. I'll try renaming my files.

**Comment by fmkguy** [comment]
Thank you so much. That was exactly the problem.

**Comment by Guspaz** [comment]
Note that if it's easier for you, you can edit the "data.json" file to change the extension it looks for to match your files. You can probably put uppercase GG in there.
