### ISSUE TITLE
Left Face Button or "Y" is mapped to button 2 and cant be unmapped (new analogue pocket firmware)

### ISSUE THREAD

**Issue by SoulSwordStrike** [spiritualized1997/openFPGA-GG#8]
The recent analogue pocket firmware now supports remapping controls, but currently by default left face button is mapped to button 2 then bottom face button to button 1 and right face button also to button 2. So if you try to assign the left face button ( Y ) to button 1 (to achieve a super gameboy type layout) it does not lose its button 2 input and you get both inputs. This default mapping of the button cant be undone and unmap all buttons does not affect it either.

**Comment by SegaSnatcher** [comment]
Yep, I noticed this on Streets of Rage 2.  The button acts like 1 and ll together if you try to map it.

**Comment by SoulSwordStrike** [comment]
Fixed now on this core and the sms one after the latest pocket firmware.
